---
- name: systemd reload
  become: yes
  command: systemctl daemon-reload

- name: restart saslauthd
  become: yes
  service:
    name: saslauthd
    state: restarted

- name: restart prosody
  become: yes
  service:
    name: prosody
    state: restarted

- name: restart jicofo
  become: yes
  service:
    name: jicofo
    state: restarted

- name: restart jvb
  become: yes
  service:
    name: jitsi-videobridge
    state: restarted

- name: restart nginx
  become: yes
  service:
    name: nginx
    state: restarted


- name: reload nginx
  become: yes
  service:
    name: nginx
    state: reloaded
