---
- name: Install Java
  include_role:
    name: common
    tasks_from: java

- name: Add jitsi repo
  include_role:
    name: common
    tasks_from: jitsi_repo

- name: Preconfigure Videobridge
  debconf:
    name: jitsi-videobridge
    question: jitsi-videobridge/jvb-hostname
    vtype: string
    value: "{{ meet_domain }}"

# - name: Preconfigure Videobridge II
#   debconf:
#     name: jitsi-videobridge
#     question: jitsi-videobridge/jvb-jvbsecret
#     vtype: password
#     value: "{{ meet_domain }}"

# tune systemd
- include: systemd_tuning.yml

- name: Install Videobridge
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - jitsi-videobridge2

- name: Configure videobridge I
  template:
    src: videobridge_sip-communicator.properties
    dest: /etc/jitsi/videobridge/sip-communicator.properties
    owner: jvb
    group: jitsi
    mode: 0600
  tags:
    - jvbconf
  notify:
    - restart jvb

# 644 con una clave... sssstupendo
- name: Configure videobridge II
  template:
    src: "{{ item }}"
    dest: /etc/jitsi/videobridge/{{ item }}
    owner: jvb
    group: jitsi
    mode: 0644
  with_items:
    - config
    - jvb.conf
  tags:
    - jvbconf
  notify:
    - restart jvb

- name: Increase TaskMax
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultTasksMax=
    line: DefaultTasksMax=65000
  notify:
    - systemd reload

- name: Increase NOFILE
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultLimitNOFILE=
    line: DefaultLimitNOFILE=65000
  notify:
    - systemd reload

- name: Increase NPROC
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultLimitNPROC=
    line: DefaultLimitNPROC=65000
  notify:
    - systemd reload

- meta: flush_handlers
