---
- name: Install Java
  include_role:
    name: common
    tasks_from: java

- name: Add jitsi repo
  include_role:
    name: common
    tasks_from: jitsi_repo

- name: Preconfigure Videobridge
  become: yes
  debconf:
    name: jitsi-videobridge
    question: jitsi-videobridge/jvb-hostname
    vtype: string
    value: "{{ meet_domain }}"

# - name: Preconfigure Videobridge II
#   debconf:
#     name: jitsi-videobridge
#     question: jitsi-videobridge/jvb-jvbsecret
#     vtype: password
#     value: "{{ meet_domain }}"

- include: systemd_tuning.yml

- name: Install Videobridge
  become: yes
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - jitsi-videobridge2

- name: Configure videobridge I
  become: yes
  template:
    src: videobridge_sip-communicator.properties
    dest: /etc/jitsi/videobridge/sip-communicator.properties
    owner: jvb
    group: jitsi
    mode: 0600
  tags:
    - jvbconf
  notify:
    - restart jvb

- name: Configure videobridge II
  become: yes
  template:
    src: "{{ item }}"
    dest: /etc/jitsi/videobridge/{{ item }}
    owner: jvb
    group: jitsi
    mode: 0644
  with_items:
    - config
    - jvb.conf
  tags:
    - jvbconf
  notify:
    - restart jvb

