---
## following https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration
- name: Increase TaskMax
  become: yes
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultTasksMax=
    line: DefaultTasksMax=65000
  notify:
    - systemd reload

- name: Increase NOFILE
  become: yes
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultLimitNOFILE=
    line: DefaultLimitNOFILE=65000
  notify:
    - systemd reload

- name: Increase NPROC
  become: yes
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: DefaultLimitNPROC=
    line: DefaultLimitNPROC=65000
  notify:
    - systemd reload

- meta: flush_handlers
