---
## Required vars for central host
vault_jicofo_pass: jicofoPassword
vault_jicofo_secret: jicofoSecret
vault_exporter_xmpp_pass: exporterXmppPassword

vault_videobridge_pass: VideobridgePassword
vault_jibri_pass: JibriPassword
