channelLastN: -1
defaultLanguage: en

# Jicofo
jicofo_user: focus
jicofo_pass: "{{ vault_jicofo_pass }}"
jicofo_secret: "{{ vault_jicofo_secret }}"

## Optional components

## prometheus jvb exporter (installs docker and runs a container for it)
run_exporter_container: false
exporter_xmpp_user: prometheus
exporter_xmpp_pass: "{{ vault_exporter_xmpp_pass }}"

## Videobridge XMPP credetials (if running jvb in this host)
videobridge_user: jvb_username
videobridge_pass: "{{ vault_videobridge_pass }}"
videobridge_muc_nick: jvb_nickname
## with the default route (as in "the default IP address")
# octo_bind_address:
## network and there's some kind of NAT from this IP address to the bind_address
# octo_public_address:

## Jibri XMPP credetials (if running jibri in this host)
jibri_user: jibri_username
jibri_pass: "{{ vault_jibri_pass }}"
# Set this to something different that "videobridge_user" if you want to share
# videobridge_user and videobridge_pass across different videobridges
jibri_muc_nick: jibri_nickname

