---
- name: Preconfigure Jicofo XMPP user I
  become: yes
  ansible.builtin.debconf:
    name: jicofo
    question: jicofo/jicofo-authuser
    vtype: string
    value: "{{ jicofo_user }}"
  changed_when: False

- name: Preconfigure Jicofo XMPP user II
  become: yes
  ansible.builtin.debconf:
    name: jicofo
    question: jicofo/jicofo-authpassword
    vtype: password
    value: "{{ jicofo_pass }}"
  changed_when: False

- name: Preconfigure Jicofo component secret
  become: yes
  ansible.builtin.debconf:
    name: jicofo
    question: jicofo/jicofosecret
    vtype: password
    value: "{{ jicofo_secret }}"
  changed_when: False

- name: Preconfigure jitsi-videobridge
  become: yes
  ansible.builtin.debconf:
    name: jitsi-videobridge
    question: jitsi-videobridge/jvb-hostname
    vtype: string
    value: "{{ meet_domain }}"

- name: Preconfigure Jitsi Meet I
  become: yes
  ansible.builtin.debconf:
    name: jitsi-meet
    question: jitsi-meet/jvb-hostname
    vtype: string
    value: "{{ meet_domain }}"

