---
meet_domain: meet.example.com

le_email: office@example.com
debian_certbot: true
# Auth (none, ldap, token)
xmpp_auth: none
allow_guests: false

# Token configuration
token_auth_appid: YOUR_APP_ID
token_auth_appsecret: "{{ vault_token_auth_appsecret }}"

## LDAP configuration
saslauthd_ldap_config: |
  ldap_servers: ldap://127.0.0.1/
  ldap_search_base: ou=PEOPLE,dc=example.com,dc=ES
  ldap_filter: (uid=%u)
  ldap_version: 3
  ldap_auth_method: bind

use_included_jitsi_gpg_key: false

## Recording
enable_recording: false
add_participants_metadata: false
recording_directory: /home/jibri/recs
# Script to execute after recording is finished
recording_processing_script: /dev/null

## octo support
octo_enabled: false
octo_strategy: RegionBasedBridgeSelectionStrategy
octo_bind_port: 4096
octo_region: none
