---
- name: Install Java
  include_role:
    name: common
    tasks_from: java

- name: Add jitsi repo
  include_role:
    name: common
    tasks_from: jitsi_repo

- name: Install required utils
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - wget
      - linux-image-amd64

- include: systemd_tuning.yml

- name: Install Jibri
  become: yes
  apt:
    pkg: "{{ packages }}"
    state: present
  vars:
    packages:
      - jibri

- name: check if chrome is installed
  become: yes
  stat:
    path: /usr/bin/google-chrome-stable
  register: chrome
  check_mode: no

- import_tasks: tasks/chrome.yml
  when: chrome.stat.exists == False

- name: Chromedriver install script
  become: yes
  template:
    src: install_chrome_driver
    dest: /usr/local/bin/install_chrome_driver
    owner: root
    group: root
    mode: 0755

- name: Install chromedriver
  become: yes
  shell:
    cmd: /usr/local/bin/install_chrome_driver
    creates: /usr/bin/chromedriver

- name: Load alsa loop on boot
  become: yes
  lineinfile:
    path: /etc/modules
    regexp: snd-aloop
    line: snd-aloop

- name: Load snd-aloop or fail because of an invalid kernel
  become: yes
  command:
    cmd: modprobe snd-aloop
  changed_when: False

- name: Create chrome policies dir
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/opt
    - /etc/opt/chrome
    - /etc/opt/chrome/policies
    - /etc/opt/chrome/policies/managed


- name: Chrome policies
  become: yes
  template:
    src: managed_policies.json
    dest: /etc/opt/chrome/policies/managed/managed_policies.json
    owner: root
    group: root
    mode: 0644

- name: Jibri configuration
  become: yes
  template:
    src: config.json
    dest: /etc/jitsi/jibri/config.json
    owner: root
    group: root
    mode: 0644
  notify:
    - restart jibri

- name: Create recording dirs
  become: yes
  file:
    state: directory
    path: "{{ recording_directory }}"
    owner: jibri
    group: jitsi
    mode: 0775
  when: enable_recording

- name: Enable and start services
  become: yes
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - jibri-xorg.service
    - jibri-icewm.service
    - jibri.service
