---
# tasks file for common
#

- name: check if openjdk-8 is installed
  stat:
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  register: java8
  check_mode: no

- name: Add stretch repository
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch main
    state: present
    filename: 'local-stretch'
  when: java8.stat.exists == False  and ansible_distribution != 'Ubuntu'

- name: Install openjdk-8-jre-headless
  apt:
    name: openjdk-8-jre-headless
    state: present
  when: java8.stat.exists == False

- name: Disable stretch repository
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch main
    state: absent
    filename: 'local-stretch'
  when: java8.stat.exists == False  and ansible_distribution != 'Ubuntu'

- name: Add Jitsi packaging GPG key
  apt_key:
    url: https://download.jitsi.org/jitsi-key.gpg.key
    state: present
  tags:
    - jitsirepo
  when: not use_included_jitsi_gpg_key

- name: Add Jitsi packaging local GPG key
  apt_key:
    data: "{{ lookup('file', 'jitsi-key.gpg.key') }}"
    state: present
  tags:
    - jitsirepo
  when: use_included_jitsi_gpg_key

- name: Add Jitsi repository
  apt_repository:
    repo: deb https://download.jitsi.org stable/
    state: present
    filename: 'local-jitsi'
  tags:
    - jitsirepo
