---
- name: Add hostname
  hostname:
  become: yes
    name: meet

- name: Installation common
  become: yes
  with_item: "{{ common_name }}"
  package:
    pkg: "{{ item.name }}"
    state: latest

- name: Enable universe repository
    apt_repository:
      repo: universe
